#base_url: 'https://www.fameandpartners.com'
base_url: 'https://fandpstaging:auth4fandpstaging@staging.fameandpartners.com'
base_url_au: 'https://fandpstaging:auth4fandpstaging@staging.fameandpartners.com.au'

user_email: auto.user.fm@gmail.com
user_pwd: 1qazxcv
gmail_pwd: 1qazqwerty
user_fname: Lorem
user_lname: Ipsum

anonymous_email: overflow100182@gmail.com
anonymous_fname: Lorem
anonymous_lname: Ipsum
anonymous_pwd: 1qazqwerty


user_r_email: auto.user.fmr@gmail.com
user_r_pwd: 1qazxcv


coupon: 3000y09m01d #coupon for 30% discount


admin: andreypetrenko@thepaydock.com
admin_pwd: 1qazxcv

# Credit card:
card_number: 5520000000000000
card_name: Zaphod Beeblebrox
exp_month: 12
exp_year: 2020
cd_cvc: 123