base_url: 'https://fandpstaging:auth4fandpstaging@staging.fameandpartners.com'
base_url_au: 'https://fandpstaging:auth4fandpstaging@staging.fameandpartners.com.au'

twit_usr_name: twit_usr_fandp
twit_email: auto.user.fm@gmail.com
twit_pwd: 1qazxcv

fb_user: auto.user.fm@gmail.com
fb_pwd: 1qazxcv
fb_f_name: Fame
fb_l_name: Partner

safari_user: safari_user@fameandpartners.com
fb_safari_user: safari_lxutxom_user@tfbnw.net
safari_user_pwd: 1qazqwerty

firefox_user: firefox_user@fameandpartners.com
fb_firefox_user: firefox_skrccip_user@tfbnw.net
firefox_user_pwd: 1qazqwerty

chrome_user: chrome_user@fameandpartners.com
fb_chrome_user: chrome_hgjvwns_user@tfbnw.net
chrome_user_pwd: 1qazqwerty
chrome_afterpay_pwd: fameandpartners2016

ie_user: ie_user@fameandpartners.com
fb_ie_user: ie_lnwrkpc_user@tfbnw.net
ie_user_pwd: 1qazqwerty

coupon: SALE25 #coupon for 25% discount

spree_admin: andreyp@fameandpartners.com
admin_pwd: 1qazqwerty

# Credit card:
card_number: 5520000000000000
card_name: Zaphod Beeblebrox
exp_month: 12
exp_year: 2020
cd_cvc: 123

# Customer IO
customer_io_url: https://fly.customer.io
customer_io_login: andreypetrenko@thepaydock.com
customer_io_pwd: 1qazxcv